Add clusters-rke2 module for provisioning downstream EC2 clusters
rancher/rancher2-scaling pull request #47
Opened 2022-03-22 00:05 UTC by git-ival

2022-04-20 15:31 UTC, floatingman requested changes
Just a few minor things.

2022-04-20 17:32 UTC, git-ival commented on clusters-rke2/variables.tf
> +  default     = "v1.21.10+rke2r2"
Nope, this is correct according to the rancher2 terraform provider docs: https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster_v2#example-usage

2022-04-20 18:24 UTC, floatingman approved these changes

2022-05-03 05:24 UTC, floatingman approved these changes
Works for me.

2022-05-03 14:47 UTC, merged